# Autoencoder  Keras implementation

In [93]:
import os
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, LeakyReLU

### Define the Autoencoder

In [61]:
# The encoder template
def Encoder():
    Model = Sequential()
    
    # You can modify the architecture for your own design
    # The following is just a simple example
    Model.add(Dense(512, input_shape=(1024,)))
    Model.add(LeakyReLU())
    
    Model.add(Dense(128, input_shape=(1024,)))
    Model.add(LeakyReLU())
    
    return Model

In [62]:
# The decoder template
def Decoder(EncoderModel):
    Model = EncoderModel
    
    # You can modify the architecture for your own design
    # The following is just a simple example
    Model.add(Dense(512, input_shape=(1024,)))
    Model.add(LeakyReLU())
    
    Model.add(Dense(1024))
    Model.add(LeakyReLU())
    
    return Model

In [63]:
# The full autoencoder
def Autoencoder():
    Model = Decoder(Encoder())
    
    # You can modify the following for your own design
    Model.compile(loss='mse', optimizer='adam', metrics=['mse'])
    
    return Model

### Build the Autoencoder

In [64]:
Encoder_ = Encoder()
AE = Autoencoder()
print(AE.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 512)               524800    
_________________________________________________________________
leaky_re_lu_15 (LeakyReLU)   (None, 512)               0         
_________________________________________________________________
dense_26 (Dense)             (None, 128)               65664     
_________________________________________________________________
leaky_re_lu_16 (LeakyReLU)   (None, 128)               0         
_________________________________________________________________
dense_27 (Dense)             (None, 512)               66048     
_________________________________________________________________
leaky_re_lu_17 (LeakyReLU)   (None, 512)               0         
_________________________________________________________________
dense_28 (Dense)             (None, 1024)              525312    
__________

### Generate some toy data

In [65]:
Data = np.random.rand(100, 1024)
print(Data)

[[0.40480142 0.63155229 0.86176384 ... 0.54392087 0.07860133 0.34563289]
 [0.25742657 0.80863109 0.4202688  ... 0.2935815  0.77106573 0.04882767]
 [0.21861738 0.46088109 0.46667054 ... 0.00685809 0.47038047 0.05452987]
 ...
 [0.15834633 0.62135311 0.23446863 ... 0.73204376 0.12853852 0.97432662]
 [0.19075531 0.47284416 0.79549493 ... 0.50759263 0.99006404 0.77960858]
 [0.57437831 0.571262   0.18986724 ... 0.3009963  0.19421348 0.092414  ]]


### Fit the Autoencoder

In [92]:
AE.fit(Data, Data, epochs=5)

Epoch 1/5
100/100 [==============================] - 0s 239us/step - loss: 0.0027 - mean_squared_error: 0.0027
Epoch 2/5
100/100 [==============================] - 0s 249us/step - loss: 0.0028 - mean_squared_error: 0.0028
Epoch 3/5
100/100 [==============================] - 0s 249us/step - loss: 0.0027 - mean_squared_error: 0.0027
Epoch 4/5
100/100 [==============================] - 0s 269us/step - loss: 0.0028 - mean_squared_error: 0.0028
Epoch 5/5
100/100 [==============================] - 0s 260us/step - loss: 0.0029 - mean_squared_error: 0.0029


### Save model

In [56]:
Encoder_.save("AE_Encoder_Keras.hdf5")
AE.save("AE_Keras.hdf5")